name: CI
on:
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - build.sbt
      - .scalafmt.conf
      - project/**
      - src/**

env:
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

jobs:
  test:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19
    steps:
      - uses: actions/checkout@v4
      - run: sbt scalafmtCheckAll
      - run: sbt clean compile
